# Generated by Django 5.1.2 on 2024-10-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_alter_clothes_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=20)),
                ('profit', models.DecimalField(decimal_places=0, max_digits=20)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
